Repository ColleyProjectGroup/ColleyProjectGroup2, pull requests merged in 2023-06, with the labels that each got.

#6 Docs: Axios 기본 설정 추가
  package-lock.json
  package.json
  src/api/axios.ts
  src/api/index.ts
  vite.config.ts
Labels: documentation

#55 [메인] 뱃지 구현 및 로그인 관리 수정사항 반영
  index.html
  package-lock.json
  package.json
  src/components/App.tsx
  src/components/Badge.tsx
  src/components/Header.tsx
  src/components/NewArrival.tsx
  src/components/Products.tsx
  src/components/RecentlyList.tsx
  src/components/index.ts
  src/contexts/LoginedUserContext.tsx
  src/contexts/RecentlyContext.tsx
  src/contexts/index.tsx
  src/hooks/index.ts
  src/hooks/useLocalStorage.ts
  src/hooks/useSessionStorage.ts
  src/pages/SignInPage.tsx
  src/pages/SignUpPage.tsx
  src/styles/components/badge.module.scss
  src/styles/components/recentlyList.module.scss
  src/styles/layout/header.module.scss
  src/types/index.ts
  src/utils/CheckIsAdmin.ts
  src/utils/index.ts
Labels: documentation

#57 [마이페이지] 구조 중간 반영
  package-lock.json
  public/images/ico_coupon.png
  public/images/ico_orders.png
  public/images/ico_won.png
  src/api/index.ts
  src/api/mypageRequests.ts
  src/components/Products.tsx
  src/components/admin/Admin.tsx
  src/components/admin/index.ts
  src/components/index.ts
  src/components/mypage/MyOrderItem.tsx
  src/components/mypage/MyOrderList.tsx
  src/components/mypage/MyOrderStatus.tsx
  src/components/mypage/MyOrderSummary.tsx
  src/components/mypage/index.ts
  src/pages/MyOrders.tsx
  src/pages/Router.tsx
  src/pages/index.ts
  src/styles/abstracts/variables.scss
  src/styles/common.scss
  src/styles/components/mypage/myOrderItem.module.scss
  src/styles/components/mypage/myOrderList.module.scss
  src/styles/components/mypage/myOrderStatus.module.scss
  src/styles/components/mypage/myOrderSummary.module.scss
  src/styles/pages/myOrders.module.scss
Labels: documentation

#65 [장바구니] Feature/cart
  src/api/index.ts
  src/api/paymentRequests.ts
  src/components/App.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/cart/CartHeader.tsx
  src/components/cart/CartItem.tsx
  src/components/cart/CartList.tsx
  src/components/cart/CartProducts.tsx
  src/components/cart/CartSummary.tsx
  src/components/payment/Confirmation.tsx
  src/components/payment/PaymentMethods.tsx
  src/components/payment/PriceInfo.tsx
  src/components/payment/ProductInfo.tsx
  src/contexts/CartContext.tsx
  src/contexts/CartLoginedContext.tsx
  src/contexts/CheckedContext.tsx
  src/contexts/index.ts
  src/hooks/index.ts
  src/hooks/useCartLocalStorage.ts
  src/pages/Cart.tsx
  src/pages/ProductDetail.tsx
  src/pages/Router.tsx
  src/pages/SignInPage.tsx
  src/pages/Success.tsx
  src/pages/index.ts
  src/styles/components/cart/cartItem.module.scss
  src/styles/components/payment/PaymentMethods.module.scss
  src/styles/components/payment/ProductInfo.module.scss
  src/styles/pages/success.module.scss
  src/types/BankAccounts.interface.ts
  src/types/Cart.interface.ts
  src/types/CartProduct.interface.ts
  src/types/Products.interface.ts
  src/types/index.ts
  src/utils/CalculateDiscountedPrice.ts
Labels: documentation

#72 Feature/login
  src/api/signApi.ts
  src/components/App.tsx
  src/components/Header.tsx
  src/components/mypage/MyPageNav.tsx
  src/components/mypage/MyPageRoute.tsx
  src/components/mypage/index.ts
  src/pages/ModifyPassword.tsx
  src/pages/Router.tsx
  src/pages/index.ts
  src/styles/components/mypage/mypage.module.scss
  src/styles/components/mypage/mypageNav.module.scss
  src/styles/layout/header.module.scss
  src/styles/pages/modifyPassword.module.scss
  src/styles/pages/myOrders.module.scss
  src/types/IdInfo.interface.ts
Labels: documentation

#76 Feature/login
  src/components/Header.tsx
  src/styles/layout/header.module.scss
Labels: documentation

#83 Fix: App.tsx Cart 수정
  src/components/App.tsx
Labels: bug

#85 [상품] 스타일 수정 반영
  src/components/BestSeller.tsx
  src/components/NewArrival.tsx
  src/components/Products.tsx
  src/pages/ProductList.tsx
  src/styles/layout/BestSeller.scss
  src/styles/layout/NewArrival.scss
  src/styles/layout/ProductList.scss
Labels: bug

#87 [구매] Fix/payment
  src/api/paymentRequests.ts
  src/components/ErrorComponent.tsx
  src/components/cart/CartSummary.tsx
  src/components/payment/BankSelection.tsx
  src/components/payment/Confirmation.tsx
  src/components/payment/DaumPostCode.tsx
  src/components/payment/PaymentMethods.tsx
  src/components/payment/UserAddress.tsx
  src/contexts/UserAddressContext.tsx
  src/contexts/index.ts
  src/pages/Payment.tsx
  src/pages/ProductDetail.tsx
  src/pages/Success.tsx
  src/styles/components/errorComponent.module.scss
  src/styles/components/payment/Confirmation.module.scss
  src/styles/components/payment/DaumPostCode.module.scss
  src/styles/components/payment/UserAddress.module.scss
  src/styles/pages/signin.module.scss
  src/styles/pages/success.module.scss
  src/types/BankAccounts.interface.ts
Labels: enhancement

#89 Fix/header
  src/components/Header.tsx
  src/styles/components/Modal.module.scss
  src/styles/layout/header.module.scss
Labels: bug

#92 [구매] Payment/Success Page styles
  src/styles/components/payment/Payment.module.scss
  src/styles/components/payment/UserAddress.module.scss
  src/styles/pages/success.module.scss
Labels: enhancement

#95 [상품] 개선사항 반영
  src/api/index.ts
  src/api/productRequests.ts
  src/components/BestSeller.tsx
  src/components/NewArrival.tsx
  src/components/Products.tsx
  src/components/index.ts
  src/components/product/BestProduct.tsx
  src/components/product/ProductDetailInfoTab.tsx
  src/components/product/index.ts
  src/constants/detailTabItems.ts
  src/constants/index.ts
  src/pages/Home.tsx
  src/pages/ProductDetail.tsx
  src/pages/ProductList.tsx
  src/styles/abstracts/variables.scss
  src/styles/components/product/productDetailInfoTab.module.scss
  src/styles/layout/BestSeller.scss
  src/styles/layout/NewArrival.scss
  src/styles/layout/ProductDetail.scss
  src/styles/layout/ProductList.scss
  src/types/BestProductProps.type.ts
  src/types/index.ts
Labels: enhancement

#96 [장바구니] Fix/cart
  package-lock.json
  src/components/App.tsx
  src/components/Badge.tsx
  src/components/cart/CartItem.tsx
  src/components/cart/CartProducts.tsx
  src/components/cart/CartSummary.tsx
  src/contexts/CartContext.tsx
  src/contexts/CheckedContext.tsx
  src/contexts/ClickedContext.tsx
  src/contexts/index.ts
  src/pages/Cart.tsx
  src/styles/components/badge.module.scss
  src/styles/components/cart/cartProducts.module.scss
  src/types/Cart.interface.ts
  src/types/CartProduct.interface.ts
Labels: enhancement

#102 [Fix] 타입스크립트 에러 수정
  package-lock.json
  package.json
  src/api/paymentRequests.ts
  src/components/ColleyNews.tsx
  src/components/NewArrival.tsx
  src/components/Products.tsx
  src/components/payment/BankSelection.tsx
  src/components/payment/DaumPostCode.tsx
  src/components/payment/ProductInfo.tsx
  src/pages/SearchResults.tsx
  src/types/Address.interface.ts
  src/types/index.ts
  src/types/swiper/index.d.ts
  tsconfig.json
Labels: bug

#104 [배포/수정] Fix/deploy error
  package-lock.json
  package.json
  public/ico_coupon.png
  public/ico_orders.png
  public/ico_won.png
  public/no-photo.png
  src/components/App.tsx
  src/components/BestSeller.tsx
  src/components/Header.tsx
  src/components/admin/AdminSalesItem.tsx
  src/components/cart/CartSummary.tsx
  src/components/mypage/MyOrderItem.tsx
  src/components/mypage/MyOrderSummary.tsx
  src/components/mypage/MyPageNav.tsx
  src/components/mypage/MyPageRoute.tsx
  src/components/mypage/MyWishItem.tsx
  src/components/mypage/index.ts
  src/components/payment/BankSelection.tsx
  src/components/payment/PaymentMethods.tsx
  src/components/payment/ProductInfo.tsx
  src/pages/Home.tsx
  src/pages/MyOrders.tsx
  src/pages/Order.tsx
  src/pages/SignInPage.tsx
  src/styles/components/mypage/myOrderItem.module.scss
  src/styles/pages/success.module.scss
  tsconfig.json
  vite.config.ts
Labels: bug, enhancement

#110 [구매] Fix/deploy payment
  src/components/cart/CartItem.tsx
  src/components/cart/CartProducts.tsx
  src/components/cart/CartSummary.tsx
  src/components/payment/Confirmation.tsx
  src/components/payment/PaymentMethods.tsx
  src/types/Cart.interface.ts
  src/types/CartProduct.interface.ts
Labels: bug, enhancement

#117 [상품] 통합테스트 예외처리 추가 반영
  src/components/main/NewArrival.tsx
  src/components/product/BestProduct.tsx
  src/components/product/Products.tsx
  src/pages/product/ProductDetail.tsx
  src/styles/layout/ProductDetail.scss
Labels: bug, enhancement

#118 [PAYMENT] Redundant alert correction
  src/components/cart/CartSummary.tsx
Labels: enhancement

#122 회원가입시오류수정
  src/pages/login/SignUpPage.tsx
Labels: bug

#123 [관리자] 고객관리 주문건, 금액 계산 오류 수정
  src/api/adminRequests.ts
  src/styles/layout/ProductDetail.scss
Labels: bug

#126 onclick이벤트수정
  src/hooks/useLocalStorage.ts
  src/pages/login/SignUpPage.tsx
Labels: bug
